export default [
{ href: './html/we become what we behold/index.html', imgSrc: 'we become what we behold.jpg', name: 'we become what we behold' },
{ href: './html/idle lumber inc/index.html', imgSrc: 'idle lumber inc.jpg', name: 'idle lumber inc' },
{ href: './html/idle digging tycoon/index.html', imgSrc: 'idle digging tycoon.jpg', name: 'idle digging tycoon' },
{ href: './html/bomber royale/index.html', imgSrc: 'bomber royale.jpg', name: 'bomber royale' },
{ href: './html/blumgi paintball/index.html', imgSrc: 'blumgi paintball.jpg', name: 'blumgi paintball' },
{ href: "./html/badegg.io/index.html", imgSrc: "badegg.io.jpg", name: "badegg.io" },
{ href: "./swf/cactus mccoy/index.html", imgSrc: "cactus mccoy.jpg", name: "cactus mccoy" },
{ href: "./swf/cactus mccoy 2/index.html", imgSrc: "cactus mccoy 2.jpg", name: "cactus mccoy 2" },
{ href: "./html/terretorial.io/index.html", imgSrc: "terretorial.io.jpeg", name: "terretorial.io" },
{ href: "./html/just passing 2/index.html", imgSrc: "just passing 2.jpg", name: "just passing 2" },
{ href: "./swf/jacksmith/index.html", imgSrc: "jacksmith.jpg", name: "jacksmith" },
{ href: "./html/Pre Civilization Bronze Age/index.html", imgSrc: "Pre Civilization Bronze Age.jpg", name: "Pre Civilization Bronze Age" },
{ href: "./html/strongdog chat/index.html", imgSrc: "strongdog chat.png", name: "Strongdog Chat" },
{ href: "./html/shipo.io/index.html", imgSrc: "shipo.io.jpg", name: "shipo.io" },
{ href: "./html/conq.io/index.html", imgSrc: "conq.io.jpg", name: "conq.io" },
{ href: "./html/sheep party/index.html", imgSrc: "sheep party.jpg", name: "sheep party" },
{ href: "./html/friday night funkin/index.html", imgSrc: "friday night funkin.jpg", name: "friday night funkin" },
{ href: "./html/tanko.io/index.html", imgSrc: "tanko.io.jpg", name: "tanko.io" },
{ href: "./html/tag/index.html", imgSrc: "tag.jpg", name: "tag" },
{ href: "./html/level devil/index.html", imgSrc: "level devil.jpg", name: "level devil" },
{ href: "./html/checkers/index.html", imgSrc: "checkers.png", name: "checkers" },
{ href: "./html/gladihoppers/index.html", imgSrc: "gladdihoppers.jfif", name: "gladihoppers" },
{ href: "./html/water color sort/index.html", imgSrc: "water color sort.png", name: "water color sort" },
{ href: "./html/fireboy and watergirl 6/index.html", imgSrc: "fireboy and watergirl 6.jfif", name: "fireboy and watergirl 6" },
{ href: "./html/Fireboy and Watergirl 5/index.html", imgSrc: "Fireboy and Watergirl 5.webp", name: "Fireboy and Watergirl 5" },
{ href: "./html/Fireboy and Watergirl 4/index.html", imgSrc: "Fireboy and Watergirl 4.jfif", name: "Fireboy and Watergirl 4" },
{ href: "./html/Fireboy and Watergirl 3/index.html", imgSrc: "Fireboy and Watergirl 3.jfif", name: "Fireboy and Watergirl 3" },
{ href: "./html/Fireboy and Watergirl 2/index.html", imgSrc: "Fireboy and Watergirl 2.jfif", name: "Fireboy and Watergirl 2" },
{ href: "./html/Fireboy and Watergirl 1/index.html", imgSrc: "Fireboy and Watergirl 1.jfif", name: "Fireboy and Watergirl 1" },
{ href: "./swf/earn to die/index.html", imgSrc: "earn to die.png", name: "earn to die" },
{ href: "./html/paper minecraft ender dragon/index.html", imgSrc: "paper minecraft ender dragon.jfif", name: "paper minecraft ender dragon" },
{ href: "./html/grindcraft/index.html", imgSrc: "grindcraft.jfif", name: "grindcraft" },
{ href: "./html/pixwars 2/index.html", imgSrc: "pixwars 2.jfif", name: "pixwars 2" },
{ href: "./swf/strike force heros/index.html", imgSrc: "strke force heros.jfif", name: "strike force heros" },
{ href: "./swf/burger tycoon/index.html", imgSrc: "burger tycoon.jfif", name: "burger tycoon" },
{ href: "./swf/miragine war/index.html", imgSrc: "miragine war.jfif", name: "miragine war" },
{ href: "./html/traffic tour/index.html", imgSrc: "traffic tour.jfif", name: "traffic tour" },
{ href: "./html/superfighters/index.html", imgSrc: "superfighters.jfif", name: "superfighters" },
{ href: "./html/super liquid soccer/index.html", imgSrc: "supper liquid soccer.jfif", name: "super liquid soccer" },
{ href: "./html/spelunky/index.html", imgSrc: "spelunky.jfif", name: "spelunky" },
{ href: "./html/rabbit samurai 2/index.html", imgSrc: "rabbit samurai 2.jfif", name: "rabbit samurai 2" },
{ href: "./html/rabbit samurai/index.html", imgSrc: "rabbit samurai.jfif", name: "rabbit samurai" },
{ href: "./html/quake/index.html", imgSrc: "quake.jfif", name: "quake" },
{ href: "./html/pizza tower/index.html", imgSrc: "pizza tower.jfif", name: "pizza tower" },
{ href: "./html/party project/index.html", imgSrc: "party project.jfif", name: "party project" },
{ href: "./html/onion boy/index.html", imgSrc: "onion boy.jfif", name: "onion boy" },
{ href: "./html/NG stars/index.html", imgSrc: "NG stars.jfif", name: "NG stars" },
{ href: "./html/n-gon/index.html", imgSrc: "n-gon.png", name: "n-gon" },
{ href: "./html/gunnight/index.html", imgSrc: "gunnight.jfif", name: "gunnight" },
{ href: "./html/freefall tournament/index.html", imgSrc: "freefall tournament.jfif", name: "freefall tournament" },
{ href: "./html/fighter aircraft piolet/index.html", imgSrc: "fighter aircraft piolet.jfif", name: "fighter aircraft piolet" },
{ href: "./html/die in the dungeon/index.html", imgSrc: "die in the dungeon.png", name: "die in the dungeon" },
{ href: "./html/cannon basketball 4/index.html", imgSrc: "cannon basketball.jfif", name: "cannon basketball 4" },
{ href: "./html/burrito bison/index.html", imgSrc: "burrito bison.jfif", name: "burrito bison" },
{ href: "./html/bumpyball.io/index.html", imgSrc: "bumpyball.io.jfif", name: "bumpyball.io" },
{ href: "./html/basket legend 2020/index.html", imgSrc: "basket legend 2020.jfif", name: "basket legend 2020" },
{ href: "./html/basket and ball/index.html", imgSrc: "basket and ball.jfif", name: "basket and ball" },
{ href: "./html/adventure drivers/index.html", imgSrc: "adventure drivers.jfif", name: "adventure drivers" },
{ href: "./html/tank trouble 2/index.html", imgSrc: "tank trouble 2.jfif", name: "tank trouble 2" },
{ href: "./html/super santa kicker/index.html", imgSrc: "super santa kicker.png", name: "super santa kicker" },
{ href: "./html/solitaire/index.html", imgSrc: "solitaire.jfif", name: "solitaire" },
{ href: "./html/nitroclash.io/index.html", imgSrc: "nitroclash.io.jfif", name: "nitroclash.io" },
{ href: "./html/gravity soccer/index.html", imgSrc: "gravity soccer.jfif", name: "gravity soccer" },
{ href: "./html/going balls/index.html", imgSrc: "going balls.jfif", name: "going balls" },
{ href: "./html/falling fox/index.html", imgSrc: "falling fox.jfif", name: "falling fox" },
{ href: "./html/draw the hill/index.html", imgSrc: "draw the hill.jfif", name: "draw the hill" },
{ href: "./html/color switch/index.html", imgSrc: "color switch.png", name: "color switch" },
{ href: "./html/brawlguys.io/index.html", imgSrc: "brawlguys.io.jfif", name: "brawlguys.io" },
{ href: "./html/basketbros.io/index.html", imgSrc: "basketbros.io.jfif", name: "basketbros.io" },
{ href: "./html/ballistic/index.html", imgSrc: "ballistic.jfif", name: "ballistic" },
{ href: "./html/two-punk-racing/index.html", imgSrc: "two-punk-racing.jfif", name: "two punk racing" },
{ href: "./html/tube-jumpers/index.html", imgSrc: "tube-jumpers.jfif", name: "tube jumpers" },
{ href: "./html/tomb-of-the-mask/index.html", imgSrc: "toumb-of-the-mask.png", name: "tomb of the mask" },
{ href: "./html/tank-io/index.html", imgSrc: "tank.io.png", name: "tank.io" },
{ href: "./html/supra-speed-racing-turbo-drift/index.html", imgSrc: "supra-speed-racing-turbo-drift.jfif", name: "racing turbo drift" },
{ href: "./html/sports/index.html", imgSrc: "sports.png", name: "sports" },
{ href: "./html/sonic-revert/index.html", imgSrc: "sonic-revert.jfif", name: "sonic revert" },
{ href: "./html/pixelfoosball/index.html", imgSrc: "pixel-foosball.jfif", name: "pixel foosball" },
{ href: "./html/Penguinio/index.html", imgSrc: "penguin-io.jfif", name: "Penguin.io" },
{ href: "./html/novabilliards/index.html", imgSrc: "nova-billiards.jfif", name: "nova billiards" },
{ href: "./html/madalin-cars/index.html", imgSrc: "madalin-cars.jfif", name: "madalin cars" },
{ href: "./html/leader-strike/index.html", imgSrc: "leader-strike.jfif", name: "leader strike" },
{ href: "./html/kart-fight-io/index.html", imgSrc: "kart-fight-io.jfif", name: "kart fight.io" },
{ href: "./html/gungame-shooting-warfare-blocky-gangster/index.html", imgSrc: "gungame-shooting-warfare-blocky-gangster.jfif", name: "blocky gangster" },
{ href: "./html/grab-party-io/index.html", imgSrc: "grab-party-io.jfif", name: "grab party.io" },
{ href: "./html/getaway-shootout/index.html", imgSrc: "getaway-shootout.jfif", name: "getaway shootout" },
{ href: "./html/dunkers/index.html", imgSrc: "dunkers.png", name: "dunkers" },
{ href: "./html/drift/index.html", imgSrc: "drift.jfif", name: "drift" },
{ href: "./html/doomz-io/index.html", imgSrc: "doomz-io.jfif", name: "doomz.io" },
{ href: "./html/discus/index.html", imgSrc: "discus.jfif", name: "disc us" },
{ href: "./html/death-run-3d/index.html", imgSrc: "death-run-3d.jfif", name: "death run 3d" },
{ href: "./html/cube-flip/index.html", imgSrc: "cube-flip.jfif", name: "cube flip" },
{ href: "./html/crazy-pixel-apocalypse-3/index.html", imgSrc: "crazy-pixel-apocalypse-3.jfif", name: "pixel apocalypse" },
{ href: "./html/cleanupio/index.html", imgSrc: "cleanupio.jfif", name: "cleanup.io" },
{ href: "./html/call-of-ops-2/index.html", imgSrc: "call-of-ops-2.jfif", name: "call of ops 2" },
{ href: "./html/blocky-gun-paintball-3/index.html", imgSrc: "blocky-gun-paintball-3.jfif", name: "blocky gun paintball" },
{ href: "./html/basketball_io/index.html", imgSrc: "basketball_io.jfif", name: "basketball.io" },
{ href: "./html/baseballfury/index.html", imgSrc: "baseballfury.jfif", name: "baseball fury" },
{ href: "./html/ball-mayhem/index.html", imgSrc: "ball-mayhem.png", name: "ball mayhem" },
{ href: "./html/adofai/index.html", imgSrc: "adofai.png", name: "A Dance of Fire And Ice" },
{ href: "./html/sleepy knight/index.html", imgSrc: "sleepy knight.png", name: "sleepy knight" },
{ href: "./html/greedy mimic/index.html", imgSrc: "greedy mimic.png", name: "greedy mimic" },
{ href: "./html/sticky sorcerer/index.html", imgSrc: "sticky sourcerer.png", name: "sticky sourcerer" },
{ href: "./html/yarne/index.html", imgSrc: "yarne.png", name: "yarne" },
{ href: "./html/two timin towers/index.html", imgSrc: "two timin towers.jpg", name: "two timin towers" },
{ href: "./html/slimoban 2/index.html", imgSrc: "slimoban 2.jpg", name: "slimoban 2" },
{ href: "./html/slide fill/index.html", imgSrc: "slide fill.jpg", name: "slide fill" },
{ href: "./html/sheep/index.html", imgSrc: "sheep.png", name: "sheep" },
{ href: "./html/roll merge 3d/index.html", imgSrc: "roll merge 3d.jpg", name: "roll merge 3d" },
{ href: "./html/ordeals of december/index.html", imgSrc: "ordeals of december.jpg", name: "ordeals of december" },
{ href: "./html/one screen run 2/index.html", imgSrc: "one screen run 2.png", name: "one screen run 2" },
{ href: "./html/indestructotank gb/index.html", imgSrc: "indestructotank gb.jpg", name: "indestructotank gb" },
{ href: "./html/gaia/index.html", imgSrc: "gaia.webp", name: "gaia" },
{ href: "./html/bokdown/index.html", imgSrc: "bokdown.png", name: "bokdown" },
{ href: "./html/yin and yang/index.html", imgSrc: "yin and yang.jpg", name: "yin and yang" },
{ href: "./html/top outpost/index.html", imgSrc: "top outpost.jpg", name: "top outpost" },
{ href: "./html/spirit dungeons/index.html", imgSrc: "spirit dungeons.webp", name: "spirit dungeons" },
{ href: "./html/pixel tap dungeon/index.html", imgSrc: "pixel tap dungeon.png", name: "pixel tap dungeon" },
{ href: "./html/out of ctrl/index.html", imgSrc: "out of ctrl.jpg", name: "out of ctrl" },
{ href: "./html/mad pirate skeleton/index.html", imgSrc: "mad pirate skeleton.jpg", name: "mad pirate skeleton" },
{ href: "./html/kity builder prototype/index.html", imgSrc: "kity builder prototype.png", name: "kity builder prototype" },
{ href: "./html/jetscout boot camp/index.html", imgSrc: "jetscout boot camp.png", name: "jetscout boot camp" },
{ href: "./html/idle fill factory/index.html", imgSrc: "idle fill factory.jpg", name: "idle fill factory" },
{ href: "./html/find a way out/index.html", imgSrc: "find a way out.jpg", name: "find a way out" },
{ href: "./html/cursed travels flame of the banshee/index.html", imgSrc: "cursed travels flame of the banshee.png", name: "cursed travels flame of the banshee" },
{ href: "./html/cognite/index.html", imgSrc: "cognite.jpg", name: "cognite" },
{ href: "./html/white pen road/index.html", imgSrc: "white pen road.webp", name: "white pen road" },
{ href: "./html/space cowboy/index.html", imgSrc: "space cowboy.jpg", name: "space cowboy" },
{ href: "./html/rail connect/index.html", imgSrc: "rail connect.jpg", name: "rail connect" },
{ href: "./html/put a ring on it/index.html", imgSrc: "put a ring on it.jpg", name: "put a ring on it" },
{ href: "./html/mutual destruction/index.html", imgSrc: "mutual destruction.jpg", name: "mutual destruction" },
{ href: "./html/mini bubbles/index.html", imgSrc: "mini bubbles.jpg", name: "mini bubbles" },
{ href: "./html/leapoid/index.html", imgSrc: "leapoid.jpg", name: "leapoid" },
{ href: "./html/keyholder/index.html", imgSrc: "keyholder.jpg", name: "keyholder" },
{ href: "./html/icy north/index.html", imgSrc: "icy north.png", name: "icy north" },
{ href: "./html/evolutionary psychol/index.html", imgSrc: "evolutionary psychology.jpg", name: "evolutionary psychol" },
{ href: "./html/escape kid/index.html", imgSrc: "escape kid.webp", name: "escape kid" },
{ href: "./html/cursed travels the shattered labyrinth/index.html", imgSrc: "cursed travels the shattered labyrinth.png", name: "cursed travels the shattered labyrinth" },
{ href: "./html/crystal wizards/index.html", imgSrc: "crystal wizards.jpg", name: "crystal wizards" },
{ href: "./html/calturin/index.html", imgSrc: "calturin.jpg", name: "calturin" },
{ href: "./html/binary/index.html", imgSrc: "binary.png", name: "binary" },
{ href: "./html/are you human/index.html", imgSrc: "are you human.webp", name: "are you human" },
{ href: "./html/anyek the keyboard puzzle/index.html", imgSrc: "anyek the keyboard puzzle.jpg", name: "anyek the keyboard puzzle" },
{ href: "./html/adventure boy jailbreak/index.html", imgSrc: "adventure boy jailbreak.jpg", name: "adventure boy jailbreak" },
{ href: "./swf/the impossible quiz 2/index.html", imgSrc: "the impossible quiz 2.avif", name: "the impossible quiz 2" },
{ href: "./html/shaky structure/index.html", imgSrc: "shaky structure.webp", name: "shaky structure" },
{ href: "./html/orb of creation/index.html", imgSrc: "orb of creation.jpg", name: "orb of creation" },
{ href: "./html/incub8/index.html", imgSrc: "incub8.png", name: "incub8" },
{ href: "./html/tryh4rd/index.html", imgSrc: "tryh4rd.jpg", name: "tryh4rd" },
{ href: "./html/runick/index.html", imgSrc: "runick.jpg", name: "runick" },
{ href: "./html/laqueus escape chapter 5/index.html", imgSrc: "laqueus escape chapter 5.jpg", name: "laqueus escape chapter 5" },
{ href: "./html/drag box/index.html", imgSrc: "drag box.jpg", name: "drag box" },
{ href: "./html/cloudhopper/index.html", imgSrc: "cloudhopper.webp", name: "cloudhopper" },
{ href: "./html/yarn untangled/index.html", imgSrc: "yarn untangled.jpg", name: "yarn untangled" },
{ href: "./html/towerland/index.html", imgSrc: "towerland.jpg", name: "towerland" },
{ href: "./html/the mage/index.html", imgSrc: "the mage.jpg", name: "the mage" },
{ href: "./html/telepobox 2/index.html", imgSrc: "telepobox2.jpg", name: "telepobox 2" },
{ href: "./html/snail trail/index.html", imgSrc: "snail trail.webp", name: "snail trail" },
{ href: "./html/robox/index.html", imgSrc: "robox.jpg", name: "robox" },
{ href: "./html/reel deep/index.html", imgSrc: "reel deep.webp", name: "reel deep" },
{ href: "./html/planet d4rk/index.html", imgSrc: "planet d4rk.png", name: "planet d4rk" },
{ href: "./html/moosha/index.html", imgSrc: "moosha.jpg", name: "moosha" },
{ href: "./html/may i have your attention, please/index.html", imgSrc: "may i have your attention, please.png", name: "may i have your attention, please" },
{ href: "./html/laqueus escape chapter 6/index.html", imgSrc: "laqueus escape chapter 6.avif", name: "laqueus escape chapter 6" },
{ href: "./html/house pusher/index.html", imgSrc: "house pusher.png", name: "house pusher" },
{ href: "./html/gobo desert of cubes/index.html", imgSrc: "gobo desert of cubes.jpg", name: "gobo desert of cubes" },
{ href: "./html/forward winds/index.html", imgSrc: "forward winds.png", name: "forward winds" },
{ href: "./html/fluctuoid/index.html", imgSrc: "fluctuoid.webp", name: "fluctuoid" },
{ href: "./html/cursed travels a forgotten seal/index.html", imgSrc: "cursed travels a forgotten seal.png", name: "cursed travels a forgotten seal" },
{ href: "./html/blacken slash demo/index.html", imgSrc: "blacken slash.jpg", name: "blacken slash demo" },
{ href: "./html/magirune/index.html", imgSrc: "magirune.jpg", name: "magirune" },
{ href: "./html/logica emotica/index.html", imgSrc: "logica emotica.jpg", name: "logica emotica" },
{ href: "./html/hall of palettes/index.html", imgSrc: "hall of palettes.png", name: "hall of palettes" },
{ href: "./html/nova cloudwalkers/index.html", imgSrc: "nova cloudwalkers.jpg", name: "nova cloudwalkers" },
{ href: "./html/notebook jam/index.html", imgSrc: "notebook jam.jpg", name: "notebook jam" },
{ href: "./html/gods of defense/index.html", imgSrc: "gods of defense.jpg", name: "gods of defense" },
{ href: "./html/slide box/index.html", imgSrc: "slide box.png", name: "slide box" },
{ href: "./html/sector 01/index.html", imgSrc: "sector 01.jpg", name: "sector 01" },
{ href: "./html/erase box/index.html", imgSrc: "erase box.jpg", name: "erase box" },
{ href: "./html/sum lines/index.html", imgSrc: "sum lines.webp", name: "sum lines" },
{ href: "./html/strg snek/index.html", imgSrc: "strg snek.png", name: "strg snek" },
{ href: "./html/rotate box/index.html", imgSrc: "rotate box.jpg", name: "rotate box" },
{ href: "./html/red scarf platformer/index.html", imgSrc: "red scarf platformer.jpg", name: "red scarf platformer" },
{ href: "./html/peeper reaper/index.html", imgSrc: "peeper reaper.jpg", name: "peeper reaper" },
{ href: "./html/ninja auto run/index.html", imgSrc: "ninja auto run.webp", name: "ninja auto run" },
{ href: "./html/murder is game over/index.html", imgSrc: "murder is game over.jpg", name: "murder is game over" },
{ href: "./html/mirror wizard/index.html", imgSrc: "mirror wizard.jpg", name: "mirror wizard" },
{ href: "./html/mini swim/index.html", imgSrc: "mini swim.jpg", name: "mini swim" },
{ href: "./html/mini flips/index.html", imgSrc: "mini flips.jpg", name: "mini flips" },
{ href: "./html/marcus osnail/index.html", imgSrc: "marcus osnail.png", name: "marcus osnail" },
{ href: "./html/knights blade/index.html", imgSrc: "knights blade.webp", name: "knights blade" },
{ href: "./html/infinite night the cunning princess/index.html", imgSrc: "infinite night the cunning princess.jpg", name: "infinite night the cunning princess" },
{ href: "./html/in space/index.html", imgSrc: "in space.jpg", name: "in space" },
{ href: "./html/hummin out/index.html", imgSrc: "hummin out.webp", name: "hummin out" },
{ href: "./html/haunted rooms/index.html", imgSrc: "haunted rooms.webp", name: "haunted rooms" },
{ href: "./html/darkraid delilah/index.html", imgSrc: "darkraid delilah.jpg", name: "darkraid delilah" },
{ href: "./html/cordovan/index.html", imgSrc: "cordovan.webp", name: "cordovan" },
{ href: "./html/contractomaton/index.html", imgSrc: "contractomaton.jpg", name: "contractomaton" },
{ href: "./html/arrow box/index.html", imgSrc: "arrow box.webp", name: "arrow box" },
{ href: "./html/viscous ventures/index.html", imgSrc: "viscous ventures.jpg", name: "viscous ventures" },
{ href: "./html/steel and claw/index.html", imgSrc: "steel and claw.png", name: "steel and claw" },
{ href: "./html/slime knight/index.html", imgSrc: "slime knight.avif", name: "slime knight" },
{ href: "./html/platformation/index.html", imgSrc: "platformation.jpg", name: "platformation" },
{ href: "./html/path of arrows/index.html", imgSrc: "path of arrows.jpg", name: "path of arrows" },
{ href: "./html/ninja kite/index.html", imgSrc: "ninja kite.jpg", name: "ninja kite" },
{ href: "./html/mutato potato/index.html", imgSrc: "mutato potato.avif", name: "mutato potato" },
{ href: "./html/mini rocket/index.html", imgSrc: "mini rocket.avif", name: "mini rocket" },
{ href: "./html/magnet master redux/index.html", imgSrc: "magnet master redux.jpg", name: "magnet master redux" },
{ href: "./html/inversion/index.html", imgSrc: "inversion.jpg", name: "inversion" },
{ href: "./html/handle/index.html", imgSrc: "handle.jpg", name: "handle" },
{ href: "./html/dispersal vectors/index.html", imgSrc: "dispersal vectors.jpg", name: "dispersal vectors" },
{ href: "./html/cata catapult/index.html", imgSrc: "cata catapult.png", name: "cata catapult" },
{ href: "./html/astro steve adventure/index.html", imgSrc: "astro steve adventure.jpg", name: "astro steve adventure" },
{ href: "./swf/elephant rave 2/index.html", imgSrc: "elephant rave 2.webp", name: "elephant rave 2" },
{ href: "./html/the designer/index.html", imgSrc: "the designer.jpg", name: "the designer" },
{ href: "./html/stress chess/index.html", imgSrc: "stress chess.jpg", name: "stress chess" },
{ href: "./html/specters of the sun/index.html", imgSrc: "specters of the sun.jpg", name: "specters of the sun" },
{ href: "./html/space order mine/index.html", imgSrc: "space order mine.jpg", name: "space order mine" },
{ href: "./html/scraplegs/index.html", imgSrc: "scraplegs.webp", name: "scraplegs" },
{ href: "./html/last plant on earth/index.html", imgSrc: "last plant on earth.webp", name: "last plant on earth" },
{ href: "./html/gloop/index.html", imgSrc: "gloop.webp", name: "gloop" },
{ href: "./html/doubleup/index.html", imgSrc: "doubleup.webp", name: "doubleup" },
{ href: "./html/toms trial/index.html", imgSrc: "toms trial.jpg", name: "toms trial" },
{ href: "./html/knights blade/index.html", imgSrc: "knights blade.webp", name: "knights blade" },
{ href: "./html/jetpack kiwi/index.html", imgSrc: "jetpack kiwi.jpg", name: "jetpack kiwi" },
{ href: "./html/dungeon scroller/index.html", imgSrc: "dongeon scroller.jpg", name: "dungeon scroller" },
{ href: "./html/a maniac/index.html", imgSrc: "a maniac.webp", name: "a maniac" },
{ href: "./html/pixelshooter/index.html", imgSrc: "pixelshooter.jpeg", name: "Pixel shooter" },
{ href: "./html/polytrack/index.html", imgSrc: "polytrack.jfif", name: "Poly track" },
{ href: "./html/infinitecraft/index.html", imgSrc: "infinitecraft.png", name: "infinite craft" },
{ href: "./html/retro bowl college/index.html", imgSrc: "retro bowl college.png", name: "retro bowl college" },
{ href: "./html/jptragar/web/index.html", imgSrc: "agar.jpeg", name: "agar.io" },
{ href: "https://jman1593.github.io/agar/", imgSrc: "agarskin.webp", name: "agar.io skins" },
{ href: "./html/giraffe/index.html", imgSrc: "giraffe.png", name: "giraffes volleyball" },
{ href: "./swf/duck life tresure hunt/index.html", imgSrc: "duck life tresure hunt.png", name: "duck life tresure hunt" },
{ href: "./html/un evergreen/index.html", imgSrc: "un evergreen.png", name: "un evergreen" },
{ href: "./html/super gauntlent/index.html", imgSrc: "super gauntlent.jpg", name: "super gauntlent" },
{ href: "./html/slis/index.html", imgSrc: "slis.webp", name: "slis" },
{ href: "./html/mini magbot/index.html", imgSrc: "mini magbot.jpg", name: "mini magbot" },
{ href: "./html/driftmania/index.html", imgSrc: "driftmania.png", name: "driftmania" },
{ href: "./html/club tycoon/index.html", imgSrc: "club tycoon.jpg", name: "club tycoon" },
{ href: "./html/blasting marbles/index.html", imgSrc: "blasting marbles.jpg", name: "blasting marbles" },
{ href: "./html/deepest sword/index.html", imgSrc: "deepest sword.jpg", name: "deepest sword" },
{ href: "./html/sort the court/index.html", imgSrc: "sort the court.jpg", name: "sort the court" },
{ href: "./html/resent/Resent-4.0-Patch-2-English.html", imgSrc: "resent.png", name: "Resent client (mc)" }
];
